version: '3.1'

services:
  history_mysql:
    image: mysql:latest
    container_name: history_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: history_db
    ports:
      - "3308:3306"

  history_server:
    build: .
    container_name: history_server
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - history_mysql
    environment:
      - DATABASE_URL=mysql+asyncmy://root:root@history_mysql/history_db
      - PRODUCTION=true
